### PR TITLE
EVDOC01-28 Identificar NESES al Roster de CV

### PR DESCRIPTION
**Pull request by stetsche**

### CODE REVIEW

**Comment by mpellicer** [comment]
This PR is failing in their local development environment, there's a startup error.

`org.sakaiproject.portal.api.PortalHandlerException: java.lang.IllegalArgumentException: Unable to find registered context for tool with ID sakai.site.roster2`

**Comment by mpellicer** [comment]
El error debe venir de más arriba, no figura roster2 en el contexto porque ha fallado previamente.

@stetsche , do you know if there's any startup error if you disable the demo mode?

**Comment by mpellicer** [comment]
More info @stetsche, it's probably related to the demo mode.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.sakaiproject.roster.api.SakaiProxy' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Cannot resolve reference to bean 'org.sakaiproject.user.api.CandidateDetailProvider' while setting bean property 'candidateDetailProvider'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.sakaiproject.user.api.CandidateDetailProvider' availabl

**Comment by stetsche** [comment]
So far I can't reproduce this locally by commenting out the properties or setting them to false. I will need to look at the differences between compact `sakaiud/compact20x` and `sakai/22x`.

**Comment by stetsche** [comment]
@mpellicer Right, it's related to the demo mode, I can reproduce it

**Comment by stetsche** [comment]
Agregué un compromiso al PR #3  para solucionar este problema

**Pull request merged**
